project_name: vals
builds:
  - id: shoal
    main: ./cmd/shoal
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mumoshu/shoal.Version={{.Version}}
changelog:
  filters:
    # commit messages matching the regexp listed here will be removed from
    # the changelog
    # Default is empty
    exclude:
      - '^docs:'
      - typo
